apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kylin-query
  namespace: kylin-prod
spec:
  serviceName: kylin-svc
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kylin
    - key: query
      operator: In
      values:
      - "true"
    - key: job
      operator: In
      values:
      - "false"
  template:
    metadata:
      labels:
        app: kylin
        query: "true"
        job: "false"
    spec:
      containers:
      - name: kylin
        image: kylin-cdh5:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        args:
        - cp $KYLIN_HOME/tomcat-config/* $KYLIN_HOME/tomcat/conf;
          cp $KYLIN_HOME/kylin-more-config $KYLIN_HOME/tomcat/webapps/kylin/WEB-INF/classes/
          $TOOL_HOME/bootstrap.sh server -d;
        ports:
        - containerPort: 7070
        - containerPort: 7443
        volumeMounts:
        - name: kylin-query-config
          mountPath: /home/apache_kylin/kylin/conf
        - name: tomcat-config
          mountPath: /home/apache_kylin/kylin/tomcat-config
        - name: kylin-more-config
          mountPath: /home/apache_kylin/kylin/kylin-more-config/
        - name: kylin-logs
          mountPath: /home/apache_kylin/kylin/logs
        - name: tomcat-logs
          mountPath: /home/apache_kylin/kylin/tomcat/logs
        resources:
          requests:
            memory: 3Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 2
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.4.3
        args:
        - -c
        - /usr/share/filebeat/config/filebeat.yml
        - -e
        volumeMounts:
        - name: kylin-logs
          mountPath: /home/apache_kylin/kylin/logs
        - name: tomcat-logs
          mountPath: /home/apache_kylin/kylin/tomcat/logs
        - name: filebeat-config
          mountPath: /usr/share/filebeat/config
          readOnly: true
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
      volumes:
      - name: kylin-logs
        emptyDir:
          sizeLimit: 3Gi
      - name: tomcat-logs
        emptyDir:
          sizeLimit: 2Gi
      - configMap:
          name: hadoop-config
        name: hadoop-config
      - configMap:
          name: hive-config
        name: hive-config
      - configMap:
          name: hbase-config
        name: hbase-config
      - configMap:
          name: kylin-query-config
        name: kylin-query-config
      - configMap:
          name: tomcat-config
        name: tomcat-config
      - configMap:
          name: filebeat-config
        name: filebeat-config
      - configMap:
          name: kylin-more-config
        name: kylin-more-config