apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kylin-receiver
  namespace: kylin-prod
spec:
  serviceName: receiver-svc
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
        - kylin-receiver
  template:
    metadata:
      labels:
        app: kylin-receiver
    spec:
      securityContext:
        fsGroup: 996
      containers:
      - name: kylin
        image: kylin-cdh5:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        args:
        - $TOOL_HOME/bootstrap.sh streaming -d
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: kylin-receiver-config
          mountPath: /home/apache_kylin/kylin/conf
        - name: receiver-volume
          mountPath: /home/apache_kylin/kylin/stream_index
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
      volumes:
        - configMap:
            name: hadoop-config
          name: hadoop-config
        - configMap:
            name: hive-config
          name: hive-config
        - configMap:
            name: hbase-config
          name: hbase-config
        - configMap:
            name: kylin-receiver-config
          name: kylin-receiver-config
  volumeClaimTemplates:
  - metadata:
      name: receiver-volume
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-dynamic