apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kylin-memcached
  namespace: kylin-prod
spec:
  serviceName: cache-svc
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kylin-memcached
  template:
    metadata:
      labels:
        app: kylin-memcached
    spec:
      containers:
      - image: memcached:1.4.39
        name: memcached
        ports:
        - containerPort: 11211
        args:
        - "-m 20480"
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 5
          timeoutSeconds: 1