apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kylin-memcached
  namespace: kylin-example
spec:
  serviceName: cache-svc
  replicas: 1
  selector:
    matchLabels:
      app: kylin-memcached
      role: cache
  template:
    metadata:
      labels:
        app: kylin-memcached
        role: cache
    spec:
      containers:
      - image: memcached:1.4.39
        name: memcached
        ports:
        - containerPort: 11211
        args:
        - "-m 20480"
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 5
          timeoutSeconds: 1