version: "3.3"

services:
  write-kafka:
    image: ${KAFKA_IMAGETAG:-bitnami/kafka:2.0.0}
    container_name: write-kafkabroker
    hostname: write-kafkabroker
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=write-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - write_kylin
    ports:
      - 9092:9092

networks:
  write_kylin:
    external: true