version: "3.3"

services:
  write-hbase-master:
    image: ${HBASE_MASTER_IMAGETAG:-bde2020/hbase-master:1.0.0-hbase1.2.6}
    container_name: write-hbase-master
    hostname: write-hbase-master
    env_file:
      - write-hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "write-namenode:50070 write-datanode1:50075 write-datanode2:50075 write-datanode3:50075 write-zookeeper:2181"
    networks:
      - write_kylin
    ports:
      - 16010:16010

  write-hbase-regionserver1:
    image: ${HBASE_REGIONSERVER_IMAGETAG:-bde2020/hbase-regionserver:1.0.0-hbase1.2.6}
    container_name: write-hbase-regionserver1
    hostname: write-hbase-regionserver1
    env_file:
      - write-hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: write-hbase-regionserver1
      SERVICE_PRECONDITION: "write-namenode:50070 write-datanode1:50075 write-datanode2:50075 write-datanode3:50075 write-zookeeper:2181 write-hbase-master:16010"
    networks:
      - write_kylin

  write-hbase-regionserver2:
    image: ${HBASE_REGIONSERVER_IMAGETAG:-bde2020/hbase-regionserver:1.0.0-hbase1.2.6}
    container_name: write-hbase-regionserver2
    hostname: write-hbase-regionserver2
    env_file:
      - write-hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: write-hbase-regionserver2
      SERVICE_PRECONDITION: "write-namenode:50070 write-datanode1:50075 write-datanode2:50075 write-datanode3:50075 write-zookeeper:2181 write-hbase-master:16010"
    networks:
      - write_kylin

networks:
  write_kylin:
    external: true
